id: P003171
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:44:59.621691
source_metadata:
  id: bdr:W1CZ1876
  title: ལམ་འབྲས་བླ་མ་ཚད་མའི་རྣམ་ཐར་
  author: ''
  volumes:
    e02a86bfb7c3424b8519c9dbe9e3be74:
      image_group_id: I1CZ1959
      title: ''
      volume_number: 1
      total_pages: 84
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
