id: IB4CD9999
legacy_id: P003171
ocr_import_info:
  bdrc_scan_id: W1CZ1876
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T00:32:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:06:39.853156+00:00'
last_modified: 2022-08-31 03:06:52.026422
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1876
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1876
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་འབྲས་བླ་མ་ཚད་མའི་རྣམ་ཐར།
statistics:
  ocr_word_mean_confidence_index: 0.3662919365088858
  ocr_word_median_confidence_index: 0.25
quality: null
bases:
  I1CZ1959:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1959
      total_pages: 84
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1959.txt
    statistics:
      ocr_word_median_confidence_index: 0.25
      ocr_word_mean_confidence_index: 0.3662919365088858
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
